urls.py
from django.conf.urls.defaults import *
from myom2.views import *
from myom2.yardsigns.views import *  
from myom2.account.views import *  
import os.path, sys

from myom2.yardsigns.feeds import *
from myom2.yardsigns.json import *

feeds = {
    'latest': LatestEntries,
}


urlpatterns = patterns('',
	(r'^$', main_page),  
	(r'^submit/$', add_sign),
	(r'^submit/thanks/$', sign_thanks),
	
	(r'^signs/$', view_scroll),
	(r'^signs/(\d+)/$', view_scroll),
	
	(r'^signs/thumbs/$', view_thumbs),
	(r'^signs/thumbs/(\d+)/$', view_thumbs),
	#single sign
	(r'^sign/(\d+)/$', view_sign),
	(r'^sign/(\d+)/embed/$', view_sign_embed),
	
	
	(r'^logout/$', logout_page),
	(r'^account/logout/$', logout_page),
	
	(r'^login/$', register_page),
	(r'^account/register/$', register_page),
	(r'^account/$', manage_account),
	
	(r'^account/delete_sign/(\d+)/$', delete_sign),
	
	
	(r'^account/update/$', update_account),
	(r'^account/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'account/password_change.html'}),
	(r'^account/password_change/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'account/password_change_done.html'}),
	
	(r'^account/password_reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'account/password_reset.html','email_template_name':'account/password_email.html'}),
	(r'^account/password_reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'account/password_reset_done.html'}),
	
	
	(r'^feeds/(?P<url>.*)/$','django.contrib.syndication.views.feed', {'feed_dict': feeds}),
	
	(r'^json/$', JsonEntries),
	
	
	(r'^admin/', include('django.contrib.admin.urls')),
	
	

	
	#hack for development, serves static files as site_media, http://www.djangoproject.com/documentation/static_files/
	(r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'files'), 	'show_indexes': True}),
	
	
	#comments
	#(r'^comments/', include('django.contrib.comments.urls.comments')),
	

)

account/forms.py
from django import newforms as forms
import re  #regex library
from django.contrib.auth.models import User 
from django.core.exceptions import ObjectDoesNotExist
from choices import *




class RegistrationForm(forms.Form): 
	email = forms.EmailField(label='E-mail address') 
	password1 = forms.CharField( label='Password', widget=forms.PasswordInput() ) 
	password2 = forms.CharField( label='Password (Again)', widget=forms.PasswordInput() )
	username = forms.CharField(label='Display name', max_length=30) 
	street_address = forms.CharField(required=False)
	city = forms.CharField()
	state = forms.ChoiceField(required=True,choices=STATE_CHOICES)
	country = forms.ChoiceField(required=True,choices=COUNTRY_CHOICES)
	zip = forms.CharField(label="Zip code", max_length=5,required=False)
	url = forms.URLField(label="Your web site", max_length=200,required=False)
	
	# makes sure the passwords match
	def clean_password2(self): 
		if 'password1' in self.cleaned_data: 
			password1 = self.cleaned_data['password1'] 
			password2 = self.cleaned_data['password2'] 
			if password1 == password2: 
				return password2 
			raise forms.ValidationError('Passwords do not match.') 

	# makes sure the username is unique
	def clean_username(self): 
		username = self.cleaned_data['username'] 
		# if not re.search(r'^\w+$', username): 
		# 		raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.') 
		try: 
			User.objects.get(username=username) 
		except ObjectDoesNotExist: 
			return username 
		raise forms.ValidationError('That display name is already taken.') 
	
	def clean_email(self):
		email = self.cleaned_data['email'] 
		try: 
			User.objects.get(email=email) 
		except ObjectDoesNotExist: 
			return email 
		raise forms.ValidationError('That e-mail address is already in use.')
		
	def clean(self):
		if self.cleaned_data.has_key('country'):
			if self.cleaned_data['country'] == 'US' and self.cleaned_data['state'] == 'XX':
				raise forms.ValidationError('US residents must specify a state.') 
			else:
				return self.cleaned_data



class UpdateRegistrationForm(forms.Form): 
	#user_pk = forms.IntegerField(widget=forms.HiddenInput(),label='')
	email = forms.EmailField(label='E-mail address') 
	username = forms.CharField(required=True,label='Display name', max_length=30)
	street_address = forms.CharField(required=False)
	city = forms.CharField()
	state = forms.ChoiceField(required=True,choices=STATE_CHOICES)
	country = forms.ChoiceField(required=True,choices=COUNTRY_CHOICES)
	zip = forms.CharField(label="Zip code", max_length=5,required=False)
	url = forms.URLField(label="Your web site", max_length=200,required=False)
	
	def clean_username(self): 
		username = self.cleaned_data['username'] 
		try: 
			#currentUser = User.objects.get(id=self.cleaned_data['user_pk'])
			currentUser = self.data['user']
			userQuery = User.objects.get(username=username) 
			if (currentUser == userQuery):
				return username
			else:
				raise forms.ValidationError('That display name is already taken.')
		except ObjectDoesNotExist: 
			return username 
		raise forms.ValidationError('That display name is already taken.') 
	
	def clean_email(self):

		
		email = self.cleaned_data['email'] 
		try: 
			#currentUser = User.objects.get(id=self.cleaned_data['user_pk'])
			currentUser = self.data['user']
			userQuery = User.objects.get(email=email) 
			if (currentUser == userQuery):
				return email
			else:
				raise forms.ValidationError('That e-mail address is already in use.')
		except ObjectDoesNotExist: 
			return email 
		raise forms.ValidationError('That e-mail address is already in use.')
	
	
	def clean(self):
		if self.cleaned_data.has_key('country'):
			if self.cleaned_data['country'] == 'US' and self.cleaned_data.has_key('state'):
				if self.cleaned_data['state'] == 'XX':
					raise forms.ValidationError('US residents must specify a state.') 
				else:
					return self.cleaned_data	
			else:
				return self.cleaned_data
				


				
class loginWithEmailForm(forms.Form):
	email = forms.EmailField(label='Email address') 
	password = forms.CharField( label='Password', widget=forms.PasswordInput()) 
	
	def clean_email(self):
		email = self.cleaned_data['email'] 
		try: 
			user = User.objects.get(email=email) 
			if user:
				return email
			else: 
				raise forms.ValidationError('That email address is not known.')
		except ObjectDoesNotExist: 
			raise forms.ValidationError('That e-mail address is not known.')
		
	# def clean_password(self):
	# 		pass
		
	def clean(self):
		from django.contrib.auth import login, authenticate, logout
		if self.cleaned_data.has_key('email'):
			try:
				tempUser = User.objects.get(email=self.cleaned_data['email'])  
				user = authenticate(username=tempUser.username, password=self.cleaned_data['password'])
				if user == None: 
					raise forms.ValidationError('That e-mail address and password combination is not valid')
				else:
					return self.cleaned_data
			except ObjectDoesNotExist:
				raise forms.ValidationError('That e-mail address and password combination is not valid')
		else:
			raise forms.ValidationError('That e-mail address is not known.')
			

templates/includes/hide_state_fields.html
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function(){
				$("li.non_field_error").each(function(){
					if ( $(this).text()== 'US residents must specify a state.'){
						newSel = $('select#id_state').parent();
						newSel.addClass('error');
						newSel.prepend('<span class="error">US residents must specify a state.</span>');
						$(this).hide();
					}
				})
			});
		</script>

templates/includes/nav.html
<div id="nav">
	<a href="/about/">About the Project</a> 
	<a href="/requirements/" class="step">Design Requirements</a> &rarr;  
	<a href="/submit/" class="step">Submit New Design</a> &rarr;  
	<a href="/signs/">View Signs</a>
	<a href="/login/">Log In</a>
</div>

templates/includes/privacy.html
<h3 class="underline">We respect your privacy</h3>

<p>
	Any personal details submitted to My Yard Our Message will be kept for the duration of the project, for the purposes of the project only, and not shared with any third parties. We will use your information in the following ways:
</p>

<dl>
	<dt>Your e-mail address</dt>
	<dd>We will use this to send you an e-mail message when voting for the project opens, when signs are available for purchase, or for notification if you are winner.</dd> 

	
	<dt>Your name</dt>
	<dd>To display near your sign during voting and for display purposes on the website.</dd>
	
	<dt>Your physical address</dt>
	<dd>So that we may display a map of where sign designers come from. You do not have to enter a street address, but we do request a city, state, and country.</dd>
	
</dl>

templates/includes/sign_thumb_loop.html
{% load thumbnail %}
<li>
	<div class="signleSignImage">
		<a href="/sign/{{sign.id}}/"><img src="/files/{{ sign.image|thumbnail:"width=180" }}" width="180"  class="singleSignImageFile"/></a>
		<h4>{{sign.title}}</h4>
		
			<h5>by 
				{% if sign.user.get_profile.url %}
					<a href="{{sign.user.get_profile.url}}">{{sign.user.username}}</a>
				{% else %}
					{{sign.user.username}}
				{% endif %}
			</h5>
		
		
		
		{% if delete %}
			<a href="delete_sign/{{sign.id}}">Delete sign</a>
		{% endif %}
		
	 	{% if not sign.approved %}
			<br /><strong>This sign has been un-approved and will not appear publicly.</strong>
		{% endif %}
	</div>
</li>

templates/includes/sponsors.html
<div id="sponsors">
	My Yard Our Message is sponsored by<br />
	<a href="http://mnartists.org/" class="sponsors_mnartists"></a>
	<a href="http://walkerart.org/" class="sponsors_walker"></a>
	<a href="http://theunconvention.com/" class="sponsors_unconvention"></a>
</div>

templates/includes/topBox_tagline.html
	<div id="tagline">
		<h2>Create and submit your designs now</h2>
		<h2>Vote on signs starting July 1st</h2>
		<h2>Order winning signs in August</h2>
	</div>
	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
			$('#tagline').innerfade({
				timeout: 5000,
				type: 'sequence',
				containerheight: '2em'
			});
		});
	</script>
	
	

templates/includes/tos.html
<br />
<h3 class="underline">Terms of Agreement</h3>

<p>
	By submitting a sign and agreeing to these terms of service you agree that the work you are submitting is free of any copyright restrictions, or is used under a license that allows for redistribution of the work. Work submitted must be licensed under the <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/" title="Creative Commons 
    Attribution-Noncommercial-Share Alike 3.0 United States">Creative Commons Attribution-Noncommercial-Share Alike License</a> which states:</p>
	<br />
	<h3>You are free:</h3>

	<ul>
		<li><strong>to Share</strong> — to copy, distribute, display, and perform the work</li>
		<li><strong>to Remix</strong> — to make derivative works</li>
	</ul>
	<br />
	
	
	<h3>Under the following conditions:</h3>

	<ul>
		<li><strong>Attribution.</strong> You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work).</li>
		<li><strong>Noncommercial.</strong> You may not use this work for commercial purposes.</li>
		<li><strong>Share Alike.</strong> If you alter, transform, or build upon this work, you may distribute the resulting work only under the same or similar license to this one.</li>
	</ul>